### ISSUE TITLE
chore(repo-health): TS errors + corrupted identifiers on main blocking Validate

### ISSUE THREAD

**Issue by PodJamz** [PodJamz/8gent-code#1883]
## Symptom

`tsc --noEmit` on `main` is failing on PRs that don't touch the offending files. Surfaced first on PR #1880 (Phase 1 daemon channel; pure additive in `packages/daemon/`).

## Errors observed

Two categories.

### Category A: ordinary TS rot

- `packages/tools/debounce.ts` — `Type 'Timeout' is not assignable to type 'number'`
- `packages/tools/duration.ts` — implicit `any` index signatures (multiple)
- `packages/tools/event-bus.ts` — `Cannot redeclare exported variable 'EventBus'`
- `packages/tools/observable.ts` — private member access errors
- `packages/tools/option.ts`, `packages/tools/result.ts` — `isolatedModules` re-export type issues
- `packages/voice/voice-chat.ts` — missing required `apiKey` field
- `packages/validation/evidence.ts` — `string | undefined` not assignable to `string`/`PathLike`
- `packages/toolshed/tools/repo/repo-tools.ts` — implicit `any` parameters

### Category B: source corruption (more serious)

- `packages/tools/structured-log.ts:56` — `Property 'current位' does not exist` (Chinese character mid-identifier)
- `packages/tools/test-runner.ts:140` — `Cannot find name 'total意图'` (Chinese characters mid-identifier)

These look like AI-typed identifiers slipped in via a bad merge. Need to grep `main` for any other mixed-script identifiers and fix.

## Fix

One housekeeping PR addressing Category A (mechanical TS fixes) and Category B (rename corrupted identifiers to ASCII).

## Why this matters

Every in-flight PR's `Validate` job is failing on these errors regardless of what the PR touches. This is also a CI signal-to-noise problem: when the type check is always red, real regressions are invisible.

## Owner

Whoever has 30 min for grunt work. Or the harness-agent next time we spawn it.
